FROM node:20-alpine AS base
RUN corepack enable
WORKDIR /app

FROM base AS deps
COPY package.json pnpm-lock.yaml pnpm-workspace.yaml turbo.json ./
COPY apps/web/package.json apps/web/
COPY apps/worker/package.json apps/worker/
COPY packages/sdk-js/package.json packages/sdk-js/
COPY packages/cli/package.json packages/cli/
COPY scripts/package.json scripts/
RUN pnpm install --frozen-lockfile || pnpm install --no-frozen-lockfile

FROM base AS builder
COPY --from=deps /app/node_modules ./node_modules
COPY . .
RUN pnpm --filter @hook-relay/web build \
  && pnpm --filter @hook-relay/web exec esbuild lib/db/migrate.ts --bundle --platform=node --format=cjs --outfile=/out/migrate.cjs \
  && pnpm --filter @hook-relay/web exec esbuild lib/db/seed.ts   --bundle --platform=node --format=cjs --outfile=/out/seed.cjs

FROM node:20-alpine AS runner
WORKDIR /app
ENV NODE_ENV=production
COPY --from=builder /out /out
COPY --from=builder /app/apps/web/drizzle ./drizzle
COPY --from=builder /app/apps/web/.next/standalone ./
COPY --from=builder /app/apps/web/.next/static ./apps/web/.next/static
COPY --from=builder /app/apps/web/public ./apps/web/public
COPY apps/web/scripts/railway-entry.sh /app/entrypoint.sh
RUN chmod +x /app/entrypoint.sh
EXPOSE 3000
CMD ["/app/entrypoint.sh"]
